[package]
name = "rocket-simples"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["secrets"] }
rocket_dyn_templates = { version = "0.2.0", features = ["tera"] }
figment = "=0.10.18"
serde = { version = "1.0.204", features = ["derive"] }
